# site settings
title: Cristian
subtitle: Quintero
email: craquinterogo@gmail.com
description: This is my professional webpage, sharing my profile and work in quantitative finance and software development.
baseurl: / # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: "Warsaw"
city: "Warsaw"
state: WAR
zip_code: 
country: Poland
phone: (+48) 539 641 920 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/craquinterogo/quantitative_finance
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: "https://www.linkedin.com/in/craquinterogo/?locale=en_US"
pinterest_url:
slack_url:
twitter_url: https://twitter.com/_arleyquintero

# build settings
markdown: kramdown

sass:
  style: compressed
